---
title: "Final Poster Figures"
author: "Xingyao Chen"
date: "7/19/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)

```

Install Necessary Pakcages and Load Data
```{r cars}
#install_github("ggbiplot", "vqv")
#library(ggbiplot)
library(lme4)
#install.packages('dplyr')
library(dplyr)
library(devtools)
#devtools::install_github("strengejacke/sjPlot",force = TRUE)
library(sjPlot)
library(sjmisc)
library(reshape2)
library(ggplot2)
library(car)

setwd('../bee')
logData=read.csv('pollinator_visitation_fullData_logTrans.csv')
```

Test Significant of the Difference Between Honeybees Visiting Small vs Large Plants
```{r}
data_dt=split(logData, logData$Date)
#Make a dataframe, summing visits for small and large plants
ttest=data.frame()
for(i in 1:length(data_dt)){
  add=data.frame(Date=names(data_dt)[i],LargeVisit=sum(data_dt[[i]]$Visits&data_dt[[i]]$Size=='Large'), SmallVisit=sum(data_dt[[i]]$Visits&data_dt[[i]]$Size=='Small'))
  ttest=rbind(ttest, add)
}
#peek
ttest
```
#Plot and perform one-tailed t test
```{r, warnings=F}
t.test(ttest$LargeVisit, ttest$SmallVisit, alternative='greater')
tmelt=melt(ttest)

ggplot(tmelt, aes(x=Date, y=value, fill=variable))+geom_bar(stat='identity', position='dodge')+theme_classic()
```

#Make Scatter Plots of Honeybees vs Date, Separated by Large and Small Plants
```{r, warnings=F}
theshold=c()
wholedf=data.frame()
for( i in 1:length(data_dt)){
  theshold[i]=median(data_dt[[i]]$Honeybees)
  data_dt[[i]]$Median=theshold[i]
  wholedf=rbind(wholedf, data_dt[[i]])
}
logData=wholedf

ggplot(data=logData, aes(x='', y=Honeybees, color=Size))+
  geom_jitter(width = 0.15)+
  facet_grid(~Date)+
  geom_hline(aes(yintercept = Median),lty=5, size=0.8)+
  labs(x="Days", size=4)+
  theme_classic()+
  theme(axis.title=element_text(size=14), legend.title=element_text(size=14),legend.text=element_text(size=12))
```


#Linear Modeling with Mixed Effects

```{r}
mylogit <- lmer(Honeybees ~
                  Avg.open.flowers.per.inflorescence+
                  Total.inflorescenses+
                  Sugar_content+
                  height+
                  (1|Date), data=logData)

summary(mylogit)
an=Anova(mylogit)
pvals=round(an$`Pr(>Chisq)`,4)
```
#Plot Results
```{r}

sjp.setTheme()
vars=c('Avg.open.flowers.per.inflorescence','Total.inflorescenses','Sugar_content',
       'height')
tit=c('Reward+Efficiency','Poential Reward for Colony', 'Reward per Inflorescense','Salience')


for(i in 1:length(vars)){
  ploot2=sjp.lmer(mylogit, type = "pred", facet.grid = FALSE,
                  vars = c(vars[i],'Date'), prnt.plot=F,show.ci=T)
  ploot2=ploot2[[2]]+
    labs(x=vars[i])+
    ggtitle(tit[i], subtitle=paste0("(p-val = ",pvals[i],')'))+
    theme_classic()+
    scale_color_brewer(palette = 'Paired')+
    theme(title=element_text(size=14, face='bold'),axis.title=element_text(size=14), legend.title=element_text(size=14),legend.text=element_text(size=12))
  #pdf(paste0('forPoster/lmerFull_diffSlope2_',vars[i],'.pdf'))
  plot(ploot2)
  #dev.off()
  #graphics.off()
}


```